"""The frozen Step-0 V2 interop vector, and every change that must break it.

The vector is what the two teams hash independently, so it is not an internal
convenience: if these bytes drift, a counted Step-0 fails at the opponent with
nothing to read but a mismatched tag.

**Generated by production code, never assembled by hand (D71).** The declaration
below is built from semantic values and rendered by the production core
extractor and canonicalizer. An earlier fixture *was* hand-built, carried
`cpu_freq_ghz` as a JSON string, and both teams reproduced bytes that neither
implementation could actually emit - which is the whole reason this file exists.
"""

import hashlib
import hmac
from dataclasses import replace
from decimal import Decimal

import pytest

from mars777_thief.app.artifact_values import GitCommitSha, UtcTimestamp
from mars777_thief.app.declaration_values import (
    Declaration,
    DeclarationTeams,
    DeclarationTimes,
)
from mars777_thief.app.protocol_errors import LocalDefectError
from mars777_thief.app.team_declaration_values import (
    HardwareDeclaration,
    RepositoryLinks,
    RoleCommits,
    TeamDeclaration,
)
from mars777_thief.protocol.canonical import canonical_json_bytes
from mars777_thief.protocol.declaration import step0_core

FAKE_SECRET = b"test-only-counted-auth-secret"
"""A published test key. The real counted secret never appears in a test."""

PREIMAGE_LEN = 732
PREIMAGE_SHA256 = "f135f40bcbe5002de423d0508cba49ffef26e0d18525d5f38af00a397601a74f"
EXPECTED_HMAC = "07246bbe1efa3509b0891f2da78542aa15d44d05390c121ca9ab6f69a5b9731f"

POLICE_COMMIT = "57622d841727f588dee45665b48c487dd6ee556f"
THIEF_COMMIT = "0e330cc5b6bc36002d21c475699cbf954c68217d"


def declaration() -> Declaration:
    """The agreed fixture as semantic values - the only hand-written part."""
    team = TeamDeclaration(
        "MaRs-777",
        "MaRs-777",
        ("Mohamed Awad", "Rawey Sleiman"),
        RepositoryLinks(
            "https://github.com/mohammedawad99/mars-777-police-agent",
            "https://github.com/mohammedawad99/mars-777-thief-agent",
        ),
        "https://example.invalid/mcp",
        HardwareDeclaration("Linux", 8, Decimal("2.4"), 16, False, None),
        "none-deterministic-agent",
        "1.02",
        RoleCommits(GitCommitSha(POLICE_COMMIT), GitCommitSha(THIEF_COMMIT)),
    )
    return Declaration(
        "MaRs-777-vs-s82kma9e",
        "43994252-2e4d-2b5c-9baa-4bf7aef5b5d6",
        100000,
        DeclarationTimes(UtcTimestamp("2026-08-23T12:00:00Z"), None),
        DeclarationTeams(team, None),
    )


def preimage(value: Declaration) -> bytes:
    """Exactly what the HMAC covers: the context prefix and the canonical core."""
    return b"step0" + canonical_json_bytes(step0_core(value, "MaRs-777"))


def tag_of(value: Declaration) -> str:
    return hmac.new(FAKE_SECRET, preimage(value), hashlib.sha256).hexdigest()


def test_the_frozen_preimage_length_is_reproduced() -> None:
    assert len(preimage(declaration())) == PREIMAGE_LEN


def test_the_frozen_preimage_digest_is_reproduced() -> None:
    assert hashlib.sha256(preimage(declaration())).hexdigest() == PREIMAGE_SHA256


def test_the_frozen_tag_is_reproduced_and_verifies() -> None:
    assert tag_of(declaration()) == EXPECTED_HMAC
    assert hmac.compare_digest(tag_of(declaration()), EXPECTED_HMAC)


def test_the_core_renders_the_cpu_frequency_as_a_json_number() -> None:
    """The exact defect that invalidated the previous vector.

    `cpu_freq_ghz` crosses the wire as canonical text but is a `Decimal` in the
    core, and the canonical form renders it as a bare JSON number. A quoted
    string here is a different preimage and therefore a different game.
    """
    body = canonical_json_bytes(step0_core(declaration(), "MaRs-777")).decode()
    assert '"cpu_freq_ghz":2.4' in body
    assert '"cpu_freq_ghz":"2.4"' not in body


def test_the_core_carries_both_role_commits_and_omits_the_other_slot() -> None:
    body = canonical_json_bytes(step0_core(declaration(), "MaRs-777")).decode()
    assert f'"github_commits":{{"police":"{POLICE_COMMIT}","thief":"{THIEF_COMMIT}"}}' in body
    assert "group_b" not in body
    assert "game_end" not in body


def _with_team(value: Declaration, **changes: object) -> Declaration:
    team = replace(value.teams.group_a, **changes)  # type: ignore[type-var]
    return replace(value, teams=DeclarationTeams(team, None))


def test_a_trailing_zero_in_the_frequency_is_a_different_preimage() -> None:
    """`2.4` and `2.40` are numerically equal and canonically distinct."""
    hardware = replace(declaration().teams.group_a.hardware, cpu_freq_ghz=Decimal("2.40"))
    assert tag_of(_with_team(declaration(), hardware=hardware)) != EXPECTED_HMAC


@pytest.mark.parametrize(
    "commits",
    [
        RoleCommits(GitCommitSha("0" * 40), GitCommitSha(THIEF_COMMIT)),
        RoleCommits(GitCommitSha(POLICE_COMMIT), GitCommitSha("1" * 40)),
        RoleCommits(GitCommitSha(THIEF_COMMIT), GitCommitSha(POLICE_COMMIT)),
    ],
    ids=["wrong police commit", "wrong thief commit", "commits swapped"],
)
def test_a_wrong_or_swapped_role_commit_breaks_the_tag(commits: RoleCommits) -> None:
    assert tag_of(_with_team(declaration(), github_commits=commits)) != EXPECTED_HMAC


def test_a_declaration_without_our_subtree_is_refused_before_any_tag() -> None:
    """Stronger than a different tag: there is nothing of ours to authenticate.

    Renaming the declared group does not quietly produce another preimage - the
    core extractor cannot find a subtree this group authored and refuses, so a
    misfiled declaration fails as a local defect rather than as a mismatch the
    opponent has to diagnose.
    """
    changed = _with_team(declaration(), group_id="s82kma9e")
    with pytest.raises(LocalDefectError):
        preimage(changed)


def test_changing_the_endpoint_or_version_breaks_the_tag() -> None:
    assert tag_of(_with_team(declaration(), mcp_endpoint="https://other.invalid/mcp")) != (
        EXPECTED_HMAC
    )
    assert tag_of(_with_team(declaration(), code_version="1.01")) != EXPECTED_HMAC


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("game_uid", "00000000-0000-0000-0000-000000000000"),
        ("token_budget_per_series", 200000),
    ],
)
def test_changing_a_series_wide_member_breaks_the_tag(field: str, value: object) -> None:
    assert tag_of(replace(declaration(), **{field: value})) != EXPECTED_HMAC


def test_changing_the_start_time_breaks_the_tag() -> None:
    times = DeclarationTimes(UtcTimestamp("2026-08-24T12:00:00Z"), None)
    assert tag_of(replace(declaration(), times=times)) != EXPECTED_HMAC


def test_a_different_context_prefix_breaks_the_tag() -> None:
    """The domain separator is part of the preimage, not decoration."""
    core = canonical_json_bytes(step0_core(declaration(), "MaRs-777"))
    other = hmac.new(FAKE_SECRET, b"config" + core, hashlib.sha256).hexdigest()
    assert other != EXPECTED_HMAC


def test_the_tag_is_lowercase_hex() -> None:
    assert EXPECTED_HMAC.lower() == EXPECTED_HMAC
    assert tag_of(declaration()) != EXPECTED_HMAC.upper()
